### ISSUE TITLE
Client Meeting 10/19 --Questions & Response

### ISSUE THREAD

**Issue by Jhowardmsstate** [Intro-to-SE-Lab-Fall-20/Group-13#32]
Client Questions
--------------------------------
1. Can email addresses be case-sensitive?
2. Is the password stored in a hash?
3. What happens subscription to Nylas ends?
4. What could be the consequences or threats of using HTML templates when not developed properly?
5. What happens when I click an attachment?
6.  What happens when an email is bounced for any unknown reasons?

**Comment by cwgu** [comment]
· Can email addresses be case-sensitive?

Email addresses are case sensitive to how entered.

· Is the password stored in a hash?

Yes, it is stored in a hash and the candidate password is hashed and tested for match, so the password is never in plain text after entering.


What happens subscription to Nylas ends. 

This software requires Nylas to be active to continue operation.


· What could be the consequences or threats of using HTML templates when not developed properly?
Errors will be visible to client. It is important to have these files complete.

What happens when I click an attachment?

As requested it is set to download.

What happens when an email is bounced for any unknown reasons?

It is based on the issues on your base email provider.
